"""empty message

Revision ID: 591c50a1353c
Revises: 
Create Date: 2018-07-06 00:14:12.998568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591c50a1353c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('pet', sa.String(length=60), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
